name: MWO4 deploy to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3 # przygotowujemy środowisku
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0
        
      - name: Restore dependences  # robimy restore
        run: dotnet restore
      
      - name: Build  #potem builda
        run: dotnet build --no-restore
        
      - name: Publish
        run: dotnet publish -c Release -o Files\dotnet/api
      
      - name: Upload Artifact  # zipujemy porjekt
        uses: actions/upload-artifact@v3
        with:
          name: personsApi-artifact
          path: Files\dotnet/api
        
  deploy-dev:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url}}  # Okreslamy url aplikacji (Azure WebApp)
    steps:
      - name: Download a Build Artifact #pobieramy zip
        uses: actions/download-artifact@v3
        with:
          name: personsApi-artifact
          
      - name: Azure WebApp #uploadujemy do Azure
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'AplikacjaWeb' # nazwa aplikacji w azure
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }} #uzywamy secrets przchowujący profil publikacji
        
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }} #okreslamy url aplikacji (Azure WebApp)
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: personsApi-artifact
          
      - name: Azure WebApp #uploadujemy do Azure
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: "MWO4"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }} #uzywamy secrets przchowujacy profil publikacji
